#!/bin/bash

set -ex

cd $(dirname $0)
python3 -m venv venv
. venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

if [ -e /sys/firmware/devicetree/base/model ] && grep -i "Raspberry Pi" /sys/firmware/devicetree/base/model
then
  pip install RPi.GPIO
fi
